// Generated by Wrangler by running `wrangler types`

interface Env {
	ENVIRONMENT: "dev" | "production";
	VOTING_OBJECT: DurableObjectNamespace<import("./src/index").VotingObject>;
}
declare module "*.sql" {
	const value: string;
	export default value;
}