name = "voting"
main = "src/index.ts"
compatibility_date = "2025-01-04"
vars = { ENVIRONMENT = "dev" }

[[durable_objects.bindings]]
name = "VOTING_OBJECT"
class_name = "VotingObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["VotingObject"]

[[rules]] 
type = "Text"
globs = ["**/*.sql"]
fallthrough = true

[env.production]
vars = { ENVIRONMENT = "production" }
