name = "openvote-api"
main = "src/index.ts"
compatibility_date = "2025-03-17"
compatibility_flags = ["nodejs_compat"]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["VotingObject"]

[observability.logs]
enabled = true

[[rules]]
type = "Text"
globs = ["**/*.sql"]
fallthrough = true

# These are repeated due to defaults
# being unable to flow to different
# environments currently in wrangler
[vars]
ENVIRONMENT = "dev"
CLERK_SECRET_KEY = ""
AUTH_SECRET_KEY = ""
INIT_SEAT = ""

[[durable_objects.bindings]]
name = "VOTING_OBJECT"
class_name = "VotingObject"

[env.dev.vars]
ENVIRONMENT = "dev"
CLERK_SECRET_KEY = ""
AUTH_SECRET_KEY = ""
INIT_SEAT = ""

[[env.dev.durable_objects.bindings]]
name = "VOTING_OBJECT"
class_name = "VotingObject"

[env.prod.vars]
ENVIRONMENT = "prod"
CLERK_SECRET_KEY = ""
AUTH_SECRET_KEY = ""
INIT_SEAT = ""

[[env.prod.durable_objects.bindings]]
name = "VOTING_OBJECT"
class_name = "VotingObject"
