name = "openvote-api"
main = "src/index.ts"
compatibility_date = "2025-01-04"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "VOTING_OBJECT"
class_name = "VotingObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["VotingObject"]

[observability.logs]
enabled = true

[[rules]]
type = "Text"
globs = ["**/*.sql"]
fallthrough = true

[vars]
ENVIRONMENT = "dev"
CLERK_SECRET_KEY = ""
AUTH_SECRET_KEY = ""
INIT_SEAT = ""

[env.prod.vars]
ENVIRONMENT = "prod"
CLERK_SECRET_KEY = ""
AUTH_SECRET_KEY = ""
INIT_SEAT = ""

[[env.prod.durable_objects.bindings]]
name = "VOTING_OBJECT"
class_name = "VotingObject"
