name = "voting"
main = "src/index.ts"
compatibility_date = "2025-01-04"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "VOTING_OBJECT"
class_name = "VotingObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["VotingObject"]

[[rules]]
type = "Text"
globs = ["**/*.sql"]
fallthrough = true

[vars]
ENVIRONMENT = "dev"
# !Make sure not to commit
CLERK_SECRET_KEY = "PROD_KEY"
AUTH_SECRET_KEY = "PROD_KEY"

[env.production.vars]
ENVIRONMENT = "production"
