name = "api"
main = "src/index.ts"
compatibility_date = "2024-03-04"

[durable_objects]
bindings = [
  { name = "WEBSOCKET_SERVER", class_name = "WebSocketHibernationServer" },
  { name = "VOTE_SERVER", class_name = "VotingServer" },
  { name = "RATE_LIMITER", class_name = "RateLimiter" }
]

[[migrations]]
tag = "v1"
new_classes = ["WebSocketHibernationServer", "VotingServer", "RateLimiter"]
