name: Deploy API

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'client/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          secrets: |
            CLERK_SECRET_KEY
            AUTH_SECRET_KEY
            INIT_SEAT
        env:
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          AUTH_SECRET_KEY: ${{ secrets.AUTH_SECRET_KEY }}
          INIT_SEAT: ${{ secrets.INIT_SEAT }}
