name: Deploy Client

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
      - '.github/workflows/client.yml'

jobs:
  deploy:
    defaults:
      run:
        working-directory: ./client
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_ENV: ${{ inputs.environment == 'Production' && 'prod' || 'dev'}}
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Install Dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
        env:
          VITE_API_URL: https://openvote-api-prod.drub.workers.dev
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: './client'
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          environment: ${{ env.DEPLOYMENT_ENV }}
